[Match]
Distribution=fedora

[Build]
SandboxTrees=repos/tailscale.repo:/etc/yum.repos.d/tailscale.repo
SandboxTrees=repos/antigravity.repo:/etc/yum.repos.d/antigravity.repo
SandboxTrees=repos/google-cloud-cli.repo:/etc/yum.repos.d/google-cloud-cli.repo

[Content]
WithRecommends=false
Packages=
    antigravity
    libxcrypt-compat
