[Match]
Distribution=fedora

[Build]
SandboxTrees=repos/fedora-multimedia.repo:/etc/yum.repos.d/fedora-multimedia.repo

[Distribution]
Repositories=fedora-multimedia

[Content]
WithRecommends=false
Packages=
    ffmpeg
    ffmpegthumbnailer
    gstreamer1-plugins-bad-free
    gstreamer1-plugins-bad-free-libs
    gstreamer1-plugins-base
    gstreamer1-plugins-good
    lame
    lame-libs
    libavcodec
    libjxl
