[Match]
Distribution=fedora

[Build]
SandboxTrees=repos/avengemedia-dms.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:avengemedia:dms.repo

[Distribution]
Repositories=copr:copr.fedorainfracloud.org:avengemedia:dms

[Content]
WithRecommends=false
Packages=
    dms
