[Match]
Distribution=fedora

[Build]
SandboxTrees=repos/mecattaf-harnessRPM.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:mecattaf:harnessRPM.repo

[Distribution]
Repositories=copr:copr.fedorainfracloud.org:mecattaf:harnessRPM

[Content]
WithRecommends=false
Packages=
    asr-rs
    atuin
    bibata-cursor-themes
    cliamp
    cliphist
    eza
    gws
    kitty
    lisgd
    mactahoe-oled
    nwg-look
    pi
    shpool
    starship
    wl-gammarelay-rs
