[Match]
Distribution=fedora

[Content]
WithRecommends=false
Packages=
    cmake
    copr-cli
    cpio
    dbus-x11
    direnv
    fish
    gcc
    gcc-c++
    gh
    git-credential-libsecret
    git-lfs
    libadwaita
    make
    meson
    neovim
    p7zip
    pandoc
    pipx
    python3-cairo
    python3-pip
    ripgrep
    uv
    yq
    zoxide
    distrobox
    podman-compose
    podman-tui
    podmansh
    toolbox
    ramalama
    whisper-cpp
    python3-gobject
    python3-ijson
    python3-numpy
    python3-pillow
    python3-psutil
    python3-pywayland
    python3-ramalama
    python3-requests
    python3-setproctitle
    python3-watchdog
    tesseract
