[Match]
Distribution=fedora

[Content]
ExtraTrees=
    cosign.pub:/usr/share/pki/containers/harness.pub

RemoveFiles=
    /usr/lib/systemd/system/flatpak-add-fedora-repos.service
    /usr/bin/chsh
    /usr/share/applications/fcitx5-wayland-launcher.desktop
    /usr/share/applications/org.fcitx.Fcitx5*.desktop

RemovePackages=
    alacritty
    fuzzel
    mako
    PackageKit
    PackageKit-glib
    qemu-user-static
    swayidle
    ublue-os-update-services
    swaylock
    waybar
    ibus-panel
    systemd-networkd
    firefox
    firefox-langpacks
    virtualbox-guest-additions
    nvtop
    sway
    yggdrasil
    adcli
    libdnf-plugin-subscription-manager
    python3-subscription-manager-rhsm
    subscription-manager
    subscription-manager-rhsm-certificates
    console-login-helper-messages
    chrony

Packages=
    acpi
    age
    aria2
    bolt
    brightnessctl
    bluez
    bluez-tools
    caddy
    cava
    chezmoi
    cockpit
    cockpit-machines
    cockpit-networkmanager
    cockpit-podman
    cockpit-selinux
    cockpit-storaged
    cockpit-system
    dbus-daemon
    dbus-tools
    ddcutil
    default-fonts
    default-fonts-core-emoji
    fastfetch
    fcitx5-mozc
    flatpak
    fontawesome-fonts-all
    foot
    fpaste
    fzf
    gcr
    generic-logos
    git-core
    glibc-all-langpacks
    glycin-thumbnailer
    gnome-disk-utility
    gnome-icon-theme
    gnome-keyring
    gnome-keyring-pam
    gnupg2-scdaemon
    google-noto-color-emoji-fonts
    google-noto-emoji-fonts
    google-noto-fonts-common
    google-noto-sans-fonts
    google-roboto-fonts
    greetd
    greetd-selinux
    gsettings-desktop-schemas
    gst-thumbnailers
    gvfs
    ibus
    imv
    input-remapper
    kanshi
    khal
    libcamera
    libva
    libva-intel-media-driver
    libva-utils
    mesa-dri-drivers
    mesa-vulkan-drivers
    nano-default-editor
    nautilus
    nautilus-python
    ncurses
    openssh-askpass
    orca
    overpass-fonts
    overpass-mono-fonts
    pamixer
    pcp-zeroconf
    pipewire
    pipewire-alsa
    pipewire-jack-audio-connection-kit
    pipewire-pulseaudio
    playerctl
    polkit
    qt6ct
    qt6-qtmultimedia
    radeontop
    sox
    steam-devices
    tailscale
    udiskie
    unrar-free
    vlc
    vulkan-tools
    vulkan-validation-layers
    webp-pixbuf-loader
    wireplumber
    wl-clipboard
    wl-mirror
    wmctrl
    wtype
    xarchiver
    xdg-desktop-portal-gnome
    xdg-desktop-portal-gtk
    xdg-terminal-exec
    xdg-user-dirs
    xorg-x11-server-Xwayland
    xwayland-satellite
    ydotool
    ykman
    yt-dlp
    zathura
    zathura-pdf-poppler
