[Match]
Distribution=fedora

[Build]
SandboxTrees=repos/avengemedia-danklinux.repo:/etc/yum.repos.d/_copr:copr.fedorainfracloud.org:avengemedia:danklinux.repo

[Distribution]
Repositories=copr:copr.fedorainfracloud.org:avengemedia:danklinux

[Content]
WithRecommends=false
Packages=
    dgop
    dms-greeter
    danksearch
