---
name: Build ISO
on:
  schedule:
    - cron: "0 0 1 * *"
  workflow_dispatch:

jobs:
  build_iso:
    name: Build installation ISO
    runs-on: ubuntu-24.04
    permissions:
      contents: write
    timeout-minutes: 120
    steps:
      - name: Checkout
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6

      - name: Maximize build space
        uses: jlumbroso/free-disk-space@v1.3.1
        with:
          dotnet: true
          haskell: true
          docker-images: true
          swap-storage: true

      - name: Build ISO
        uses: osbuild/bootc-image-builder-action@main
        id: build
        with:
          config-file: iso.toml
          image: ghcr.io/mecattaf/harness:latest
          types: anaconda-iso

      - name: Upload ISO as artifact
        uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v5
        with:
          name: harness-iso-${{ github.run_number }}
          path: ${{ steps.build.outputs.output }}
          retention-days: 30
          if-no-files-found: error
